language: go

go:
- 1.10.x
- 1.11.x
- 1.13.x

before_install:
- wget -O dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
- chmod +x dep
- ./dep ensure -v

script:
- go test -race ./...